{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "0dc892e4-88ea-40c6-98fc-6b8d3eb02833",
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import glob\n",
    "import shutil\n",
    "import torch\n",
    "import torch.nn as nn\n",
    "import torch.nn.functional as F\n",
    "import numpy as np\n",
    "import xarray as xr\n",
    "import matplotlib.pyplot as plt\n",
    "from IPython.display import Image\n",
    "from IPython.display import display\n",
    "from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error\n",
    "from scipy.stats import gaussian_kde\n",
    "import seaborn as sns\n",
    "from scipy.stats import norm"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "94e93488-7fbe-4770-acdf-34a3feec6f44",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Define paths\n",
    "path1 = \"/work/bb1070/b382483/Data/TrainTest/ftp_stability/features_*\"\n",
    "path2 = \"/work/bb1070/b382483/Data/TrainTest/ftp_stability/labels_*\"\n",
    "model_path = '/work/bb1070/b382483/Final/L=2km_new/NewCNNmodel/ftp_stability-identity/best_model_weights.pth'"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "809cef36-e9c4-44a1-8920-cb8baa0791de",
   "metadata": {},
   "outputs": [],
   "source": [
    "save_path = \"/work/bb1070/b382483/Final/L=2km_new/Plots/BarPlot\"\n",
    "\n",
    "# Create a new, empty directory\n",
    "os.makedirs(save_path, exist_ok=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a1400fa3-1680-4361-86e3-0236c90abe04",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Mean and std for de-normalization (replace with actual values)\n",
    "mean_GRNHFX = 94.552284  # Replace with the actual mean\n",
    "std_GRNHFX = 2804.3684   # Replace with the actual std dev"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b5b85501-70c6-4245-bf8b-05604e253385",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Function to de-normalize data\n",
    "def de_normalize(data, mean, std):\n",
    "    return (data * std) + mean"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "74d01533-3510-4e62-90ff-4ca782887432",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Function to load datasets\n",
    "def load_datasets(file_index, files1, files2):\n",
    "    feature_file = files1[file_index]\n",
    "    label_file = files2[file_index]\n",
    "    ds_feature = xr.open_dataset(feature_file)\n",
    "    ds_label = xr.open_dataset(label_file)\n",
    "    return ds_feature, ds_label"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7c9dc986-b847-450b-89dc-45afb83e2848",
   "metadata": {},
   "outputs": [],
   "source": [
    "class ConcatConvBlock(nn.Module):\n",
    "    def __init__(self, in_channels, out_channels):\n",
    "        super(ConcatConvBlock, self).__init__()\n",
    "        self.conv3x3 = nn.Conv2d(in_channels, out_channels, kernel_size=3, padding=1)\n",
    "        self.conv5x5 = nn.Conv2d(in_channels, out_channels, kernel_size=5, padding=2)\n",
    "        self.conv7x7 = nn.Conv2d(in_channels, out_channels, kernel_size=7, padding=3)\n",
    "        self.pool = nn.MaxPool2d(kernel_size=2, stride=2)\n",
    "\n",
    "    def forward(self, x):\n",
    "        x1 = torch.relu(self.conv3x3(x))\n",
    "        x2 = torch.relu(self.conv5x5(x))\n",
    "        x3 = torch.relu(self.conv7x7(x))\n",
    "        x = torch.cat((x1, x2, x3), dim=1)\n",
    "        x = self.pool(x)\n",
    "        return x\n",
    "\n",
    "class SequentialCNNModel(nn.Module):\n",
    "    def __init__(self):\n",
    "        super(SequentialCNNModel, self).__init__()\n",
    "        self.model = nn.Sequential(\n",
    "            ConcatConvBlock(93, 16),    # Block 1\n",
    "            ConcatConvBlock(48, 32),    # Block 2\n",
    "            ConcatConvBlock(96, 64),    # Block 3\n",
    "            ConcatConvBlock(192, 128),  # Block 4\n",
    "            ConcatConvBlock(384, 256),  # Block 5\n",
    "            nn.Flatten(),               # Block 6\n",
    "            nn.Linear(768 * 7 * 15, 128), # Block 7, adjusted based on the output of Block 5\n",
    "            nn.ReLU(),\n",
    "            nn.Dropout(0.3),\n",
    "            nn.Linear(128, 256),        # Block 7\n",
    "            nn.ReLU(),\n",
    "            nn.Dropout(0.3),\n",
    "            nn.Linear(256, 250 * 500),  # Block 7\n",
    "            #nn.ReLU()\n",
    "            nn.Identity()\n",
    "        )\n",
    "        self.reshape = (250, 500)\n",
    "\n",
    "    def forward(self, x):\n",
    "        x = self.model(x)\n",
    "        x = x.view(-1, *self.reshape)\n",
    "        return x"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b80a2e87-bcef-4c5c-b57d-8d7d959457ec",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Function to generate predictions and de-normalize\n",
    "def generate_predictions(model, ds_feature, mean_GRNHFX, std_GRNHFX, device):\n",
    "    predictions = []\n",
    "    with torch.no_grad():\n",
    "        for time_step in range(len(ds_feature['Time'])):\n",
    "            X = ds_feature.isel(Time=time_step).to_array().values\n",
    "            if X.ndim == 4 and X.shape[0] == 1:\n",
    "                X = X.squeeze(0)\n",
    "            X_tensor = torch.tensor(X, dtype=torch.float32).to(device)\n",
    "            X_tensor = X_tensor.unsqueeze(0)  # Add batch dimension\n",
    "\n",
    "            output = model(X_tensor)\n",
    "            prediction = output.squeeze().cpu().numpy()  # Remove batch dimension and move to CPU\n",
    "\n",
    "            # De-normalize the prediction\n",
    "            prediction = de_normalize(prediction, mean_GRNHFX, std_GRNHFX)\n",
    "\n",
    "            predictions.append(prediction)\n",
    "\n",
    "    return predictions"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9debf70b-7f97-4a7a-bd31-3d981a2d868c",
   "metadata": {},
   "outputs": [],
   "source": [
    "def se_distribution(actual, predicted):\n",
    "    \n",
    "    # Flatten arrays and remove NaNs\n",
    "    error = predicted.flatten() - actual.flatten()\n",
    "    error = error[~np.isnan(error)]\n",
    "\n",
    "    # Plot histogram and KDE\n",
    "    plt.figure(figsize=(8, 5))\n",
    "\n",
    "    # Separate over and under predictions\n",
    "    #under = error[error < 0]\n",
    "    #over = error[error >= 0]\n",
    "\n",
    "    # Histogram with fewer bins and black edges\n",
    "    bins = np.linspace(-50, 50, 20)\n",
    "    #plt.hist(under, bins=bins, density=True, alpha=0.7, color='blue', edgecolor='black', label='Underprediction')\n",
    "    #plt.hist(over, bins=bins, density=True, alpha=0.7, color='red', edgecolor='black', label='Overprediction')\n",
    "    plt.hist(error, bins=bins, density=True, alpha=0.7, color='blue', edgecolor='black')\n",
    "    \n",
    "    # Labels and styling\n",
    "    plt.xlabel('Prediction Error (Predicted - Actual) [kW/m²]', fontsize=12)\n",
    "    plt.ylabel('Density', fontsize=12)\n",
    "    plt.title('Prediction Error Distribution', fontsize=14)\n",
    "    #plt.legend()\n",
    "    plt.grid(True, linestyle='--', alpha=0.3)\n",
    "    plt.xlim(-50, 50)\n",
    "    #plt.ylim(0, 0.05)\n",
    "    plt.tight_layout()\n",
    "    \n",
    "    output_path = os.path.join(save_path, \"identity_signed_error_distribution.png\")\n",
    "    plt.savefig(output_path, dpi=300)\n",
    "    plt.close()\n",
    "    print(f\"✅ Plot saved to: {output_path}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6c18cb60-c521-478b-8d6b-b2e63b212630",
   "metadata": {},
   "outputs": [],
   "source": [
    "def main():\n",
    "    files1 = sorted(glob.glob(path1))\n",
    "    files2 = sorted(glob.glob(path2))\n",
    "    \n",
    "    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n",
    "\n",
    "    model = SequentialCNNModel().to(device)\n",
    "    model.load_state_dict(torch.load(model_path, map_location=device))\n",
    "    model.eval()\n",
    "\n",
    "    all_actual_nonzero = []\n",
    "    all_predicted_nonzero = []\n",
    "\n",
    "    for idx in range(len(files1)):\n",
    "        print(f\"Processing file {idx + 1}/{len(files1)}\")\n",
    "        \n",
    "        ds_feature, ds_label = load_datasets(idx, files1, files2)\n",
    "\n",
    "        ds_label['GRNHFX'] = de_normalize(ds_label['GRNHFX'], mean_GRNHFX, std_GRNHFX)\n",
    "        \n",
    "        predictions = generate_predictions(model, ds_feature, mean_GRNHFX, std_GRNHFX, device)\n",
    "        predictions_da = xr.DataArray(\n",
    "            np.array(predictions),\n",
    "            dims=[\"Time\", \"south_north\", \"west_east\"],\n",
    "            coords={\n",
    "                \"Time\": ds_label[\"Time\"],\n",
    "                \"south_north\": ds_label[\"south_north\"],\n",
    "                \"west_east\": ds_label[\"west_east\"]\n",
    "            }\n",
    "        )\n",
    "\n",
    "        actual = ds_label['GRNHFX'].values / 1000.0\n",
    "        predicted = predictions_da.values / 1000.0\n",
    "\n",
    "        actual_flat = actual.flatten()\n",
    "        predicted_flat = predicted.flatten()\n",
    "\n",
    "        nonzero_mask = (actual_flat > 0)\n",
    "        actual_nonzero = actual_flat[nonzero_mask]\n",
    "        predicted_nonzero = predicted_flat[nonzero_mask]\n",
    "\n",
    "        all_actual_nonzero.append(actual_nonzero)\n",
    "        all_predicted_nonzero.append(predicted_nonzero)\n",
    "\n",
    "    # Concatenate all non-zero values\n",
    "    all_actual_nonzero = np.concatenate(all_actual_nonzero)\n",
    "    all_predicted_nonzero = np.concatenate(all_predicted_nonzero)\n",
    "\n",
    "    # --- Metrics ---\n",
    "    r2 = r2_score(all_actual_nonzero, all_predicted_nonzero)\n",
    "    rmse = mean_squared_error(all_actual_nonzero, all_predicted_nonzero, squared=False)\n",
    "    mae = mean_absolute_error(all_actual_nonzero, all_predicted_nonzero)\n",
    "\n",
    "    print(f\"R² Score: {r2:.4f}\")\n",
    "    print(f\"RMSE: {rmse:.4f} kW/m²\")\n",
    "    print(f\"MAE: {mae:.4f} kW/m²\")\n",
    "\n",
    "    se_distribution(all_actual_nonzero, all_predicted_nonzero)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6855991b-4c4b-4c91-a912-c0e4f37b99bd",
   "metadata": {
    "scrolled": true
   },
   "outputs": [],
   "source": [
    "if __name__ == \"__main__\":\n",
    "    main()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6387b379-bcc1-4b3b-bb24-ce251ccc746b",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "be1b8478-27f0-454b-a191-f8c40a3aff80",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "env-ubc",
   "language": "python",
   "name": "env-ubc"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.19"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
