{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "a982493d-393c-483a-bdc9-de5958504056",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Pysteps configuration file found at: /work/bb1070/b382483/ubcEnv/env-ubc/lib/python3.9/site-packages/pysteps/pystepsrc\n",
      "\n"
     ]
    }
   ],
   "source": [
    "import os\n",
    "import glob\n",
    "import torch\n",
    "import torch.nn as nn\n",
    "import numpy as np\n",
    "import xarray as xr\n",
    "from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score\n",
    "import matplotlib.pyplot as plt\n",
    "from pysteps.verification.salscores import sal"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "42643d44-b133-484a-ab57-1532cedd5796",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Paths for feature and label files\n",
    "FEATURES_PATH = \"/work/bb1070/b382483/Data/TrainTest/ftp_stability/features_*\"\n",
    "LABELS_PATH = \"/work/bb1070/b382483/Data/TrainTest/ftp_stability/labels_*\"\n",
    "\n",
    "# Model_Path\n",
    "MODEL_PATH = \"/work/bb1070/b382483/Final/L=2km_new/NewCNNmodel/ftp_stability-identity/best_model_weights.pth\"\n",
    "\n",
    "# Specify output directories\n",
    "SAL_PLOTS_DIR = \"/work/bb1070/b382483/Final/L=2km_new/Plots/SAL-Identity\"\n",
    "os.makedirs(SAL_PLOTS_DIR, exist_ok=True)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "10d9dfae-6b1d-49de-97c1-fee1ba2b250b",
   "metadata": {},
   "outputs": [],
   "source": [
    "input_channels =93\n",
    "\n",
    "# Mean and std for de-normalization (replace with actual values)\n",
    "MEAN_GRNHFX =  94.552284\n",
    "STD_GRNHFX = 2804.3684\n",
    "\n",
    "# Device configuration\n",
    "DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "08946b4f-d9bd-4b64-803a-59921abe36a4",
   "metadata": {},
   "outputs": [],
   "source": [
    "def load_datasets(features_path: str, labels_path: str):\n",
    "    features = sorted(glob.glob(features_path))\n",
    "    labels = sorted(glob.glob(labels_path))\n",
    "    return features, labels"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "6e275b17-d786-4602-91cc-4d4d457c84fe",
   "metadata": {},
   "outputs": [],
   "source": [
    "# ConcatConvBlock and SequentialCNNModel remain the same as in your original code\n",
    "class ConcatConvBlock(nn.Module):\n",
    "    def __init__(self, in_channels, out_channels):\n",
    "        super(ConcatConvBlock, self).__init__()\n",
    "        self.conv3x3 = nn.Conv2d(in_channels, out_channels, kernel_size=3, padding=1)\n",
    "        self.conv5x5 = nn.Conv2d(in_channels, out_channels, kernel_size=5, padding=2)\n",
    "        self.conv7x7 = nn.Conv2d(in_channels, out_channels, kernel_size=7, padding=3)\n",
    "        self.pool = nn.MaxPool2d(kernel_size=2, stride=2)\n",
    "\n",
    "    def forward(self, x):\n",
    "        x1 = torch.relu(self.conv3x3(x))\n",
    "        x2 = torch.relu(self.conv5x5(x))\n",
    "        x3 = torch.relu(self.conv7x7(x))\n",
    "        x = torch.cat((x1, x2, x3), dim=1)\n",
    "        x = self.pool(x)\n",
    "        return x\n",
    "\n",
    "\n",
    "class SequentialCNNModel(nn.Module):\n",
    "    def __init__(self, input_channels):\n",
    "        super(SequentialCNNModel, self).__init__()\n",
    "        self.model = nn.Sequential(\n",
    "            ConcatConvBlock(input_channels, 16),\n",
    "            ConcatConvBlock(48, 32),\n",
    "            ConcatConvBlock(96, 64),\n",
    "            ConcatConvBlock(192, 128),\n",
    "            ConcatConvBlock(384, 256),\n",
    "            nn.Flatten(),\n",
    "            nn.Linear(768 * 7 * 15, 128),\n",
    "            nn.ReLU(),\n",
    "            nn.Dropout(0.3),\n",
    "            nn.Linear(128, 256),\n",
    "            nn.ReLU(),\n",
    "            nn.Dropout(0.3),\n",
    "            nn.Linear(256, 250 * 500),\n",
    "            #nn.ReLU()\n",
    "            nn.Identity()\n",
    "        )\n",
    "        self.reshape = (250, 500)\n",
    "\n",
    "    def forward(self, x):\n",
    "        x = self.model(x)\n",
    "        x = x.view(-1, *self.reshape)\n",
    "        return x"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "954da1e7-1b13-4806-bd61-4503309f0da8",
   "metadata": {},
   "outputs": [],
   "source": [
    "# De-normalize function\n",
    "def de_normalize(data, mean, std):\n",
    "    return (data * std) + mean"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "ec85e0f9-14ff-4577-9faa-951e5937830a",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Generate predictions function\n",
    "def generate_predictions(model, ds_feature, mean, std, device):\n",
    "    predictions = []\n",
    "    with torch.no_grad():\n",
    "        for time_step in range(len(ds_feature['Time'])):\n",
    "            X = ds_feature.isel(Time=time_step).to_array().values\n",
    "            if X.ndim == 4 and X.shape[0] == 1:\n",
    "                X = X.squeeze(0)\n",
    "            X_tensor = torch.tensor(X, dtype=torch.float32).to(device).unsqueeze(0)\n",
    "            output = model(X_tensor).squeeze().cpu().numpy()\n",
    "            predictions.append(de_normalize(output, mean, std))\n",
    "    return np.array(predictions)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "b938bfcc-61f2-410c-87e9-ee6fd5c76d86",
   "metadata": {},
   "outputs": [],
   "source": [
    "def calculate_sal(predictions, actual_data, quantile: float):\n",
    "    sal_values = []\n",
    "    for pred, actual in zip(predictions, actual_data):\n",
    "        try:\n",
    "            s, a, l = sal(pred, actual, thr_factor=0.01, thr_quantile=quantile)\n",
    "        except Exception as e:\n",
    "            print(f\"SAL calculation failed for quantile {quantile}: {e}\")\n",
    "            s, a, l = np.nan, np.nan, np.nan\n",
    "        sal_values.append([s, a, l])\n",
    "    return np.array(sal_values)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "5920bb88-3566-4b65-a842-eb67aec6601f",
   "metadata": {},
   "outputs": [],
   "source": [
    "def plot_sal_evolution(structure_list, amplitude_list, location_list, dataset_idx, output_dir, quantile: float):\n",
    "    \"\"\"\n",
    "    Optimized plot for SAL parameters over time.\n",
    "    Axes for Structure (S) and Amplitude (A) are set to [-2, 2].\n",
    "    Points are connected in the order of increasing time step with a dashed line.\n",
    "    The first and last points are annotated.\n",
    "    \"\"\"\n",
    "    plt.figure(figsize=(8, 6))\n",
    "    \n",
    "    # Scatter plot for Structure (S) vs Amplitude (A), with color representing Location (L)\n",
    "    sc = plt.scatter(\n",
    "        structure_list, amplitude_list, \n",
    "        c=location_list, cmap='viridis', vmin=0, vmax=1, s=100, \n",
    "        edgecolor='k', alpha=0.8, label=\"SAL Points\"\n",
    "    )\n",
    "    \n",
    "    # Add dashed line to connect points in time order\n",
    "    plt.plot(structure_list, amplitude_list, linestyle='--', color='gray', alpha=0.7, label=\"Time Path\")\n",
    "\n",
    "    # Annotate the first and last points\n",
    "    plt.scatter([structure_list[0]], [amplitude_list[0]], color='red', edgecolor='k', s=150, label='First Time Step')\n",
    "    plt.scatter([structure_list[-1]], [amplitude_list[-1]], color='pink', edgecolor='k', s=150, label='Last Time Step')\n",
    "    plt.text(structure_list[0] + 0.1, amplitude_list[0] + 0.1, \"First\", fontsize=10, color='red')\n",
    "    plt.text(structure_list[-1] + 0.1, amplitude_list[-1] + 0.1, \"Last\", fontsize=10, color='pink')\n",
    "\n",
    "    # Axes labels and title\n",
    "    plt.xlabel(\"S (Structure)\")\n",
    "    plt.ylabel(\"A (Amplitude)\")\n",
    "    #plt.title(f\"SAL Evolution Over Time (Dataset {dataset_idx})\")\n",
    "    plt.title(f\"SAL Evolution Over Time\")\n",
    "\n",
    "    # Axes limits and reference lines\n",
    "    plt.xlim([-2, 2])\n",
    "    plt.ylim([-2, 2])\n",
    "    plt.axhline(0, color='black', linewidth=1)\n",
    "    plt.axvline(0, color='black', linewidth=1)\n",
    "\n",
    "    # Add grid, colorbar, and legend\n",
    "    cbar = plt.colorbar(sc)\n",
    "    cbar.set_label(\"L (Location)\")\n",
    "    plt.grid(alpha=0.5, linestyle='--')\n",
    "    plt.legend()\n",
    "    plt.tight_layout()\n",
    "    \n",
    "    save_path = os.path.join(output_dir, f\"{dataset_idx:03d}_SAL_Evolution_Dataset_Quantile_{quantile}.png\")\n",
    "    try:\n",
    "        plt.savefig(save_path, dpi=300)\n",
    "        print(f\"SAL plot saved at: {save_path}\")\n",
    "    except Exception as e:\n",
    "        print(f\"Error saving SAL plot for Dataset {dataset_idx}: {e}\")\n",
    "    plt.close()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "fb0e892b-7672-46f8-92bd-6893dd529de0",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Calculate SAL differences and plot\n",
    "def calculate_and_plot_sal_differences(sal_values_95, sal_values_50, dataset_idx, output_dir):\n",
    "\n",
    "    # Compute percentage difference\n",
    "    absolute_diff = np.abs(sal_values_95 - sal_values_50)\n",
    "\n",
    "    absolute_diff[:, 0] = absolute_diff[:, 0]*100/4\n",
    "    absolute_diff[:, 1] = absolute_diff[:, 1]*100/4\n",
    "    absolute_diff[:, 2] = absolute_diff[:, 2]*100\n",
    "        \n",
    "    labels = ['Structure (S)', 'Amplitude (A)', 'Location (L)']\n",
    "    plt.figure(figsize=(8, 6))\n",
    "    for i, label in enumerate(labels):\n",
    "        plt.plot(absolute_diff[:, i], label=label, marker='o')\n",
    "\n",
    "    plt.xlabel(\"Time Index\")\n",
    "    plt.ylabel(\"Absolute Difference Percentage\")\n",
    "    #plt.title(f\"SAL Absolute Difference Percentage (Dataset {dataset_idx})\")\n",
    "    plt.title(f\"SAL Absolute Difference Percentage\")\n",
    "    plt.legend()\n",
    "    plt.grid(alpha=0.5)\n",
    "    plt.tight_layout()\n",
    "\n",
    "    save_path = os.path.join(output_dir, f\"{dataset_idx:03d}_SAL_Absolute_Difference_Percentage_Dataset.png\")\n",
    "    plt.savefig(save_path, dpi=300)\n",
    "    print(f\"SAL Absolute difference plot saved at: {save_path}\")\n",
    "    plt.close()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "128302d6-5c22-42e9-8fde-5ffedbe4c4e1",
   "metadata": {},
   "outputs": [],
   "source": [
    "def process_dataset(model, idx, feature_file, label_file, output_dir):\n",
    "    ds_feature = xr.open_dataset(feature_file).load()\n",
    "    ds_label = xr.open_dataset(label_file).load()\n",
    "    ds_label['GRNHFX'] = de_normalize(ds_label['GRNHFX'], MEAN_GRNHFX, STD_GRNHFX)\n",
    "    actual_data = ds_label['GRNHFX'].values\n",
    "\n",
    "    predictions = generate_predictions(model, ds_feature, MEAN_GRNHFX, STD_GRNHFX, DEVICE)\n",
    "\n",
    "    zero_mask = (actual_data == 0)\n",
    "    predictions[zero_mask] = 0                                 # a)\n",
    "\n",
    "    predictions = np.nan_to_num(predictions, nan=0.0,\n",
    "                                 posinf=0.0, neginf=0.0)       # b)\n",
    "    actual_data = np.nan_to_num(actual_data, nan=0.0,\n",
    "                                posinf=0.0, neginf=0.0)   \n",
    "    \n",
    "    sal_values_95 = calculate_sal(predictions, actual_data, quantile=0.95)\n",
    "    sal_values_50 = calculate_sal(predictions, actual_data, quantile=0.5)\n",
    "\n",
    "    plot_sal_evolution(\n",
    "        structure_list=sal_values_95[:, 0], \n",
    "        amplitude_list=sal_values_95[:, 1], \n",
    "        location_list=sal_values_95[:, 2], \n",
    "        dataset_idx=idx, \n",
    "        output_dir=SAL_PLOTS_DIR,\n",
    "        quantile=95\n",
    "    )\n",
    "\n",
    "    plot_sal_evolution(\n",
    "        structure_list=sal_values_50[:, 0], \n",
    "        amplitude_list=sal_values_50[:, 1], \n",
    "        location_list=sal_values_50[:, 2], \n",
    "        dataset_idx=idx, \n",
    "        output_dir=SAL_PLOTS_DIR,\n",
    "        quantile=50\n",
    "    )\n",
    "\n",
    "    calculate_and_plot_sal_differences(sal_values_95, sal_values_50, idx, output_dir)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "a3b873c6-a96b-40e7-a207-cdf5a41a443e",
   "metadata": {},
   "outputs": [],
   "source": [
    "def main():\n",
    "    model = SequentialCNNModel(input_channels=input_channels).to(DEVICE)\n",
    "    model.load_state_dict(torch.load(MODEL_PATH, map_location=DEVICE))\n",
    "    model.eval()\n",
    "\n",
    "    features, labels = load_datasets(FEATURES_PATH, LABELS_PATH)\n",
    "    for idx, (feature_file, label_file) in enumerate(zip(features, labels)):\n",
    "        print(f\"Processing dataset {idx}/{len(features)}...\")\n",
    "        process_dataset(model, idx, feature_file, label_file, SAL_PLOTS_DIR)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "18ed9085-6300-4240-8688-81b6ed2e3ff5",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/tmp/ipykernel_1858262/677480813.py:3: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.\n",
      "  model.load_state_dict(torch.load(MODEL_PATH, map_location=DEVICE))\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Processing dataset 0/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/000_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/000_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/000_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 1/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/001_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/001_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/001_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 2/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/002_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/002_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/002_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 3/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/003_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/003_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/003_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 4/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/004_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/004_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/004_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 5/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/005_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/005_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/005_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 6/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/006_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/006_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/006_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 7/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/007_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/007_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/007_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 8/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/008_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/008_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/008_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 9/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/009_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/009_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/009_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 10/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/010_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/010_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/010_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 11/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/011_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/011_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/011_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 12/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/012_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/012_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/012_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 13/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/013_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/013_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/013_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 14/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/014_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/014_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/014_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 15/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/015_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/015_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/015_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 16/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/016_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/016_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/016_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 17/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/017_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/017_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/017_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 18/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/018_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/018_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/018_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 19/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/019_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/019_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/019_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 20/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/020_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/020_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/020_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 21/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/021_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/021_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/021_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 22/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/022_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/022_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/022_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 23/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/023_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/023_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/023_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 24/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/024_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/024_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/024_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 25/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/025_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/025_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/025_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 26/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/026_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/026_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/026_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 27/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/027_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/027_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/027_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 28/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/028_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/028_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/028_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 29/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/029_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/029_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/029_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 30/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/030_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/030_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/030_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 31/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/031_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/031_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/031_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 32/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/032_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/032_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/032_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 33/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/033_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/033_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/033_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 34/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/034_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/034_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/034_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 35/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/035_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/035_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/035_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 36/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/036_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/036_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/036_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 37/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/037_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/037_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/037_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 38/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/038_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/038_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/038_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 39/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/039_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/039_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/039_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 40/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/040_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/040_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/040_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 41/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/041_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/041_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/041_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 42/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/042_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/042_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/042_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 43/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/043_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/043_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/043_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 44/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/044_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/044_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/044_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 45/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/045_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/045_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/045_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 46/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/046_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/046_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/046_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 47/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/047_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/047_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/047_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 48/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/048_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/048_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/048_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 49/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/049_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/049_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/049_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 50/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/050_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/050_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/050_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 51/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/051_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/051_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/051_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 52/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/052_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/052_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/052_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 53/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/053_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/053_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/053_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 54/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/054_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/054_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/054_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 55/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/055_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/055_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/055_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 56/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/056_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/056_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/056_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 57/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/057_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/057_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/057_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 58/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/058_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/058_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/058_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 59/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/059_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/059_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/059_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 60/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/060_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/060_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/060_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 61/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/061_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/061_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/061_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 62/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/062_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/062_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/062_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 63/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/063_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/063_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/063_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 64/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/064_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/064_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/064_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 65/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/065_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/065_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/065_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 66/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/066_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/066_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/066_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 67/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/067_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/067_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/067_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 68/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/068_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/068_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/068_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 69/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/069_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/069_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/069_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 70/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/070_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/070_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/070_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 71/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/071_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/071_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/071_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 72/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/072_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/072_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/072_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 73/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/073_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/073_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/073_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 74/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/074_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/074_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/074_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 75/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/075_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/075_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/075_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 76/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/076_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/076_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/076_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 77/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/077_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/077_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/077_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 78/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/078_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/078_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/078_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 79/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/079_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/079_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/079_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 80/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/080_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/080_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/080_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 81/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/081_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/081_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/081_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 82/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/082_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/082_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/082_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 83/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/083_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/083_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/083_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 84/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/084_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/084_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/084_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 85/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/085_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/085_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/085_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 86/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/086_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/086_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/086_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 87/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/087_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/087_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/087_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 88/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/088_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/088_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/088_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 89/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/089_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/089_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/089_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 90/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/090_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/090_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/090_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 91/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/091_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/091_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/091_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 92/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/092_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/092_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/092_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 93/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/093_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/093_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/093_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 94/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/094_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/094_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/094_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 95/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/095_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/095_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/095_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 96/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/096_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/096_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/096_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 97/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/097_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/097_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/097_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 98/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/098_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/098_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/098_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 99/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/099_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/099_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/099_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 100/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/100_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/100_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/100_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 101/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/101_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/101_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/101_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 102/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/102_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/102_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/102_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 103/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/103_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/103_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/103_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 104/105...\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/104_SAL_Evolution_Dataset_Quantile_95.png\n",
      "SAL plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/104_SAL_Evolution_Dataset_Quantile_50.png\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/Plots/SAL/104_SAL_Absolute_Difference_Percentage_Dataset.png\n"
     ]
    }
   ],
   "source": [
    "if __name__ == \"__main__\":\n",
    "    main()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "fe938f02-9bfc-4912-a421-f541accb5f9f",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "env-ubc",
   "language": "python",
   "name": "env-ubc"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.19"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
