{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "a982493d-393c-483a-bdc9-de5958504056",
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import glob\n",
    "import torch\n",
    "import torch.nn as nn\n",
    "import numpy as np\n",
    "import xarray as xr\n",
    "from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score\n",
    "import matplotlib.pyplot as plt\n",
    "from matplotlib.lines import Line2D\n",
    "from pysteps.verification.salscores import sal"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "42643d44-b133-484a-ab57-1532cedd5796",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Paths for feature and label files\n",
    "FEATURES_PATH = \"/work/bb1070/b382483/Data/TrainTest/ftp_stability/features_*\"\n",
    "LABELS_PATH = \"/work/bb1070/b382483/Data/TrainTest/ftp_stability/labels_*\"\n",
    "\n",
    "# Model_Path\n",
    "MODEL_PATH = \"/work/bb1070/b382483/Final/L=2km_new/NewCNNmodel/ftp_stability-identity/best_model_weights.pth\"\n",
    "\n",
    "# Specify output directories\n",
    "SAL_PLOTS_DIR = \"/work/bb1070/b382483/Final/L=2km_new/SAL-Reviewer/Plots\"\n",
    "os.makedirs(SAL_PLOTS_DIR, exist_ok=True)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "10d9dfae-6b1d-49de-97c1-fee1ba2b250b",
   "metadata": {},
   "outputs": [],
   "source": [
    "input_channels =93\n",
    "\n",
    "# Mean and std for de-normalization (replace with actual values)\n",
    "MEAN_GRNHFX =  94.552284\n",
    "STD_GRNHFX = 2804.3684\n",
    "\n",
    "# Device configuration\n",
    "DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "id": "08946b4f-d9bd-4b64-803a-59921abe36a4",
   "metadata": {},
   "outputs": [],
   "source": [
    "def load_datasets(features_path: str, labels_path: str):\n",
    "    features = sorted(glob.glob(features_path))\n",
    "    labels = sorted(glob.glob(labels_path))\n",
    "    return features, labels"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "6e275b17-d786-4602-91cc-4d4d457c84fe",
   "metadata": {},
   "outputs": [],
   "source": [
    "# ConcatConvBlock and SequentialCNNModel remain the same as in your original code\n",
    "class ConcatConvBlock(nn.Module):\n",
    "    def __init__(self, in_channels, out_channels):\n",
    "        super(ConcatConvBlock, self).__init__()\n",
    "        self.conv3x3 = nn.Conv2d(in_channels, out_channels, kernel_size=3, padding=1)\n",
    "        self.conv5x5 = nn.Conv2d(in_channels, out_channels, kernel_size=5, padding=2)\n",
    "        self.conv7x7 = nn.Conv2d(in_channels, out_channels, kernel_size=7, padding=3)\n",
    "        self.pool = nn.MaxPool2d(kernel_size=2, stride=2)\n",
    "\n",
    "    def forward(self, x):\n",
    "        x1 = torch.relu(self.conv3x3(x))\n",
    "        x2 = torch.relu(self.conv5x5(x))\n",
    "        x3 = torch.relu(self.conv7x7(x))\n",
    "        x = torch.cat((x1, x2, x3), dim=1)\n",
    "        x = self.pool(x)\n",
    "        return x\n",
    "\n",
    "\n",
    "class SequentialCNNModel(nn.Module):\n",
    "    def __init__(self, input_channels):\n",
    "        super(SequentialCNNModel, self).__init__()\n",
    "        self.model = nn.Sequential(\n",
    "            ConcatConvBlock(input_channels, 16),\n",
    "            ConcatConvBlock(48, 32),\n",
    "            ConcatConvBlock(96, 64),\n",
    "            ConcatConvBlock(192, 128),\n",
    "            ConcatConvBlock(384, 256),\n",
    "            nn.Flatten(),\n",
    "            nn.Linear(768 * 7 * 15, 128),\n",
    "            nn.ReLU(),\n",
    "            nn.Dropout(0.3),\n",
    "            nn.Linear(128, 256),\n",
    "            nn.ReLU(),\n",
    "            nn.Dropout(0.3),\n",
    "            nn.Linear(256, 250 * 500),\n",
    "            #nn.ReLU()\n",
    "            nn.Identity()\n",
    "        )\n",
    "        self.reshape = (250, 500)\n",
    "\n",
    "    def forward(self, x):\n",
    "        x = self.model(x)\n",
    "        x = x.view(-1, *self.reshape)\n",
    "        return x"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "954da1e7-1b13-4806-bd61-4503309f0da8",
   "metadata": {},
   "outputs": [],
   "source": [
    "# De-normalize function\n",
    "def de_normalize(data, mean, std):\n",
    "    return (data * std) + mean"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "id": "ec85e0f9-14ff-4577-9faa-951e5937830a",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Generate predictions function\n",
    "def generate_predictions(model, ds_feature, mean, std, device):\n",
    "    predictions = []\n",
    "    with torch.no_grad():\n",
    "        for time_step in range(len(ds_feature['Time'])):\n",
    "            X = ds_feature.isel(Time=time_step).to_array().values\n",
    "            if X.ndim == 4 and X.shape[0] == 1:\n",
    "                X = X.squeeze(0)\n",
    "            X_tensor = torch.tensor(X, dtype=torch.float32).to(device).unsqueeze(0)\n",
    "            output = model(X_tensor).squeeze().cpu().numpy()\n",
    "            predictions.append(de_normalize(output, mean, std))\n",
    "    return np.array(predictions)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "id": "b938bfcc-61f2-410c-87e9-ee6fd5c76d86",
   "metadata": {},
   "outputs": [],
   "source": [
    "def calculate_sal(predictions, actual_data, quantile: float):\n",
    "    sal_values = []\n",
    "    for pred, actual in zip(predictions, actual_data):\n",
    "        try:\n",
    "            s, a, l = sal(pred, actual, thr_factor=0.01, thr_quantile=quantile)\n",
    "        except Exception as e:\n",
    "            print(f\"SAL calculation failed for quantile {quantile}: {e}\")\n",
    "            s, a, l = np.nan, np.nan, np.nan\n",
    "        sal_values.append([s, a, l])\n",
    "    return np.array(sal_values)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "id": "ae5218ac-d69d-435c-8850-b45471ac53b0",
   "metadata": {},
   "outputs": [],
   "source": [
    "def plot_sal_evolution_avg_only(sal_values, dataset_idx, output_dir, quantile: float,\n",
    "                                start_idx, keep_first=5, avg_window=10):\n",
    "\n",
    "    sal_path, t_path = build_averaged_path(sal_values, start_idx, keep_first, avg_window)\n",
    "\n",
    "    if sal_path.shape[0] < 2:\n",
    "        print(f\"Dataset {dataset_idx}: Not enough SAL points to plot after start_idx={start_idx}.\")\n",
    "        return\n",
    "\n",
    "    # remove rows that are NaN (cannot plot)\n",
    "    valid = np.all(np.isfinite(sal_path), axis=1)\n",
    "    sal_path = sal_path[valid]\n",
    "    t_path = t_path[valid]\n",
    "\n",
    "    if sal_path.shape[0] < 2:\n",
    "        print(f\"Dataset {dataset_idx}: All SAL points are NaN/inf after filtering.\")\n",
    "        return\n",
    "\n",
    "    S_path, A_path, L_path = sal_path[:,0], sal_path[:,1], sal_path[:,2]\n",
    "\n",
    "    plt.figure(figsize=(8,6))\n",
    "\n",
    "    norm = plt.Normalize(vmin=0, vmax=1)\n",
    "    cmap = plt.cm.viridis\n",
    "\n",
    "    sc = plt.scatter(S_path, A_path, c=L_path, cmap=cmap, norm=norm,\n",
    "                     s=140, edgecolor='k', linewidth=0.8, alpha=0.95,\n",
    "                     label=\"Averaged SAL points\")    \n",
    "\n",
    "    # Arrowed trajectory\n",
    "    for i in range(len(S_path) - 1):\n",
    "        plt.annotate(\"\", xy=(S_path[i+1], A_path[i+1]),\n",
    "                     xytext=(S_path[i], A_path[i]),\n",
    "                     arrowprops=dict(arrowstyle=\"->\", lw=2, alpha=0.75))\n",
    "\n",
    "    # First and last markers: fill by L, border red/pink\n",
    "    first_color = cmap(norm(L_path[0]))\n",
    "    last_color  = cmap(norm(L_path[-1]))\n",
    "\n",
    "    plt.scatter([S_path[0]], [A_path[0]],\n",
    "                s=280, facecolor=first_color, edgecolor='red', linewidth=3,\n",
    "                zorder=6, label=f\"First active fire time step\")\n",
    "\n",
    "    plt.scatter([S_path[-1]], [A_path[-1]],\n",
    "                s=280, facecolor=last_color, edgecolor='hotpink', linewidth=3,\n",
    "                zorder=6, label=f\"Last time step\")\n",
    "\n",
    "    plt.xlabel(\"S (Structure)\")\n",
    "    plt.ylabel(\"A (Amplitude)\")\n",
    "    plt.title(f\"SAL Evolution Over Time\")\n",
    "\n",
    "    plt.xlim([-2,2])\n",
    "    plt.ylim([-2,2])\n",
    "    plt.axhline(0, color='black', linewidth=1)\n",
    "    plt.axvline(0, color='black', linewidth=1)\n",
    "\n",
    "    cbar = plt.colorbar(sc)\n",
    "    cbar.set_label(\"L (Location)\")\n",
    "\n",
    "    plt.grid(alpha=0.35, linestyle='--')\n",
    "\n",
    "    # ---- Custom Legend ----\n",
    "\n",
    "    legend_elements = [\n",
    "\n",
    "    # Hollow circle for averaged SAL points\n",
    "        Line2D([0], [0],\n",
    "           marker='o',\n",
    "           color='black',\n",
    "           label='Averaged SAL points',\n",
    "           markerfacecolor='none',\n",
    "           markersize=10,\n",
    "           linestyle='None'),\n",
    "\n",
    "    # Hollow circle with red edge for first\n",
    "        Line2D([0], [0],\n",
    "           marker='o',\n",
    "           color='red',\n",
    "           label='First active fire time step',\n",
    "           markerfacecolor='none',\n",
    "           markersize=10,\n",
    "           linestyle='None',\n",
    "           markeredgewidth=2),\n",
    "\n",
    "    # Hollow circle with pink edge for last\n",
    "        Line2D([0], [0],\n",
    "           marker='o',\n",
    "           color='hotpink',\n",
    "           label='Last time step',\n",
    "           markerfacecolor='none',\n",
    "           markersize=10,\n",
    "           linestyle='None',\n",
    "           markeredgewidth=2),\n",
    "\n",
    "    # Arrow legend entry for time path\n",
    "        Line2D([0], [0],\n",
    "           color='black',\n",
    "           lw=2,\n",
    "           label='Time Path',\n",
    "           marker=r'$\\rightarrow$',\n",
    "           markersize=12)\n",
    "        ]\n",
    "\n",
    "    plt.legend(handles=legend_elements, loc='upper right')\n",
    "    \n",
    "    plt.tight_layout()\n",
    "\n",
    "    save_path = os.path.join(output_dir, f\"{dataset_idx:03d}_SAL_Evolution_AVG_Q{quantile}.png\")\n",
    "    plt.savefig(save_path, dpi=300)\n",
    "    plt.close()\n",
    "\n",
    "    print(f\"Dataset {dataset_idx}: start_idx={start_idx}, first plotted t≈{t_path[0]:.1f}, \"\n",
    "          f\"avg_window={avg_window} (last chunk may be smaller).\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "id": "fb0e892b-7672-46f8-92bd-6893dd529de0",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Calculate SAL differences and plot\n",
    "def calculate_and_plot_sal_differences(sal_values_95, sal_values_50, dataset_idx, output_dir):\n",
    "\n",
    "    # Compute percentage difference\n",
    "    absolute_diff = np.abs(sal_values_95 - sal_values_50)\n",
    "\n",
    "    absolute_diff[:, 0] = absolute_diff[:, 0]*100/4\n",
    "    absolute_diff[:, 1] = absolute_diff[:, 1]*100/4\n",
    "    absolute_diff[:, 2] = absolute_diff[:, 2]*100\n",
    "        \n",
    "    labels = ['Structure (S)', 'Amplitude (A)', 'Location (L)']\n",
    "    plt.figure(figsize=(8, 6))\n",
    "    for i, label in enumerate(labels):\n",
    "        plt.plot(absolute_diff[:, i], label=label, marker='o')\n",
    "\n",
    "    plt.xlabel(\"Time Index\")\n",
    "    plt.ylabel(\"Absolute Difference Percentage\")\n",
    "    #plt.title(f\"SAL Absolute Difference Percentage (Dataset {dataset_idx})\")\n",
    "    plt.title(f\"SAL Absolute Difference Percentage\")\n",
    "    plt.legend()\n",
    "    plt.grid(alpha=0.5)\n",
    "    plt.tight_layout()\n",
    "\n",
    "    save_path = os.path.join(output_dir, f\"{dataset_idx:03d}_SAL_Absolute_Difference_Percentage_Dataset.png\")\n",
    "    plt.savefig(save_path, dpi=300)\n",
    "    print(f\"SAL Absolute difference plot saved at: {save_path}\")\n",
    "    plt.close()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "id": "e8baf8e0-6f2a-4089-bab6-2236be5addc1",
   "metadata": {},
   "outputs": [],
   "source": [
    "def find_first_fire_timestep(actual_data, fire_thr=1.0, min_pixels=10):\n",
    "    \"\"\"\n",
    "    Return first timestep index where the target has at least min_pixels above fire_thr.\n",
    "    If none found, return None.\n",
    "    \"\"\"\n",
    "    for t in range(actual_data.shape[0]):\n",
    "        if np.sum(actual_data[t] > fire_thr) >= min_pixels:\n",
    "            return t\n",
    "    return None\n",
    "\n",
    "\n",
    "def find_first_valid_sal_index(sal_values, start_idx):\n",
    "    \"\"\"\n",
    "    Return first timestep >= start_idx where SAL is finite (S and A).\n",
    "    If none found, return None.\n",
    "    \"\"\"\n",
    "    for t in range(start_idx, sal_values.shape[0]):\n",
    "        s, a, l = sal_values[t]\n",
    "        if np.isfinite(s) and np.isfinite(a) and np.isfinite(l):\n",
    "            return t\n",
    "    return None\n",
    "\n",
    "\n",
    "def build_averaged_path(sal_values, start_idx, keep_first=5, avg_window=10):\n",
    "    \"\"\"\n",
    "    Create reduced SAL trajectory:\n",
    "    - keep first `keep_first` timesteps (starting at start_idx)\n",
    "    - average remaining in chunks of size avg_window (last chunk may be smaller)\n",
    "    Returns:\n",
    "      sal_path: (M,3)\n",
    "      t_path:   (M,) representative time index per point\n",
    "    \"\"\"\n",
    "    T = sal_values.shape[0]\n",
    "    if start_idx is None or start_idx >= T:\n",
    "        return np.empty((0,3)), np.array([])\n",
    "\n",
    "    # Slice from start_idx\n",
    "    sal = sal_values[start_idx:]\n",
    "\n",
    "    # Keep first points (as-is)\n",
    "    end_keep = min(keep_first, sal.shape[0])\n",
    "    kept = sal[:end_keep]\n",
    "    kept_t = np.arange(start_idx, start_idx + end_keep)\n",
    "\n",
    "    # Average remainder\n",
    "    rest = sal[end_keep:]\n",
    "    rest_start_t = start_idx + end_keep\n",
    "\n",
    "    avg_list = []\n",
    "    t_list = []\n",
    "\n",
    "    for i in range(0, rest.shape[0], avg_window):\n",
    "        chunk = rest[i:i+avg_window]  # may be < avg_window at end\n",
    "        # average ignoring NaNs\n",
    "        chunk_mean = np.nanmean(chunk, axis=0)\n",
    "        avg_list.append(chunk_mean)\n",
    "\n",
    "        # representative time = center of this chunk in original time index\n",
    "        center_t = rest_start_t + i + (len(chunk) - 1) / 2.0\n",
    "        t_list.append(center_t)\n",
    "\n",
    "    if len(avg_list) > 0:\n",
    "        avg_arr = np.vstack(avg_list)\n",
    "        t_arr = np.array(t_list)\n",
    "        sal_path = np.vstack([kept, avg_arr])\n",
    "        t_path = np.concatenate([kept_t, t_arr])\n",
    "    else:\n",
    "        sal_path = kept\n",
    "        t_path = kept_t\n",
    "\n",
    "    return sal_path, t_path"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "id": "dd1f9e00-404f-454d-8895-fac12fda2636",
   "metadata": {},
   "outputs": [],
   "source": [
    "def process_dataset(model, idx, feature_file, label_file, output_dir):\n",
    "    ds_feature = xr.open_dataset(feature_file)\n",
    "    ds_label = xr.open_dataset(label_file)\n",
    "\n",
    "    try:\n",
    "        # de-normalize target\n",
    "        actual_data = de_normalize(ds_label['GRNHFX'].values.astype(np.float32),\n",
    "                                   MEAN_GRNHFX, STD_GRNHFX)\n",
    "\n",
    "        predictions = generate_predictions(model, ds_feature, MEAN_GRNHFX, STD_GRNHFX, DEVICE)\n",
    "\n",
    "        # ---- robust fire thresholding ----\n",
    "        fire_thr = 1.0        # W/m^2 (adjust if needed)\n",
    "        min_pixels = 10       # require at least 10 burning pixels\n",
    "\n",
    "        # mask non-burning areas (threshold-based)\n",
    "        zero_mask = (actual_data <= fire_thr)\n",
    "        predictions[zero_mask] = 0.0\n",
    "\n",
    "        # clean NaNs\n",
    "        predictions = np.nan_to_num(predictions, nan=0.0, posinf=0.0, neginf=0.0)\n",
    "        actual_data = np.nan_to_num(actual_data, nan=0.0, posinf=0.0, neginf=0.0)\n",
    "\n",
    "        # compute SAL\n",
    "        sal_values_95 = calculate_sal(predictions, actual_data, quantile=0.95)\n",
    "        sal_values_50 = calculate_sal(predictions, actual_data, quantile=0.5)\n",
    "\n",
    "        # find first fire timestep (based on target)\n",
    "        first_fire_t = find_first_fire_timestep(actual_data, fire_thr=fire_thr, min_pixels=min_pixels)\n",
    "        if first_fire_t is None:\n",
    "            print(f\"Dataset {idx}: No fire detected (thr={fire_thr}, min_pixels={min_pixels}). Skipping plots.\")\n",
    "            return\n",
    "\n",
    "        # find first valid SAL index (SAL may be NaN even if fire exists)\n",
    "        start_idx_95 = find_first_valid_sal_index(sal_values_95, first_fire_t)\n",
    "        start_idx_50 = find_first_valid_sal_index(sal_values_50, first_fire_t)\n",
    "\n",
    "        if start_idx_95 is None:\n",
    "            print(f\"Dataset {idx}: No valid SAL(0.95) values after fire start. Skipping Q95 plot.\")\n",
    "        else:\n",
    "            plot_sal_evolution_avg_only(sal_values_95, idx, SAL_PLOTS_DIR, quantile=95,\n",
    "                                        start_idx=start_idx_95, keep_first=5, avg_window=10)\n",
    "\n",
    "        if start_idx_50 is None:\n",
    "            print(f\"Dataset {idx}: No valid SAL(0.5) values after fire start. Skipping Q50 plot.\")\n",
    "        else:\n",
    "            plot_sal_evolution_avg_only(sal_values_50, idx, SAL_PLOTS_DIR, quantile=50,\n",
    "                                        start_idx=start_idx_50, keep_first=5, avg_window=10)\n",
    "\n",
    "        calculate_and_plot_sal_differences(sal_values_95, sal_values_50, idx, output_dir)\n",
    "\n",
    "    finally:\n",
    "        ds_feature.close()\n",
    "        ds_label.close()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 27,
   "id": "6b023aef-872e-4ea1-8c4d-5a64f73a8c08",
   "metadata": {},
   "outputs": [],
   "source": [
    "def main():\n",
    "    model = SequentialCNNModel(input_channels=input_channels).to(DEVICE)\n",
    "    model.load_state_dict(torch.load(MODEL_PATH, map_location=DEVICE))\n",
    "    model.eval()\n",
    "\n",
    "    features, labels = load_datasets(FEATURES_PATH, LABELS_PATH)\n",
    "\n",
    "    selected_indices = [1, 47, 59, 63]\n",
    "\n",
    "    for idx in selected_indices:\n",
    "        if idx >= len(features):\n",
    "            print(f\"Index {idx} out of range. Skipping.\")\n",
    "            continue\n",
    "\n",
    "        feature_file = features[idx]\n",
    "        label_file = labels[idx]\n",
    "\n",
    "        print(f\"Processing dataset {idx}/{len(features)}...\")\n",
    "        process_dataset(model, idx, feature_file, label_file, SAL_PLOTS_DIR)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 28,
   "id": "18ed9085-6300-4240-8688-81b6ed2e3ff5",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/tmp/ipykernel_3593845/4103838551.py:3: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.\n",
      "  model.load_state_dict(torch.load(MODEL_PATH, map_location=DEVICE))\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Processing dataset 1/105...\n",
      "Dataset 1: start_idx=2, first plotted t≈2.0, avg_window=10 (last chunk may be smaller).\n",
      "Dataset 1: start_idx=2, first plotted t≈2.0, avg_window=10 (last chunk may be smaller).\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/SAL-Reviewer/Plots/001_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 47/105...\n",
      "Dataset 47: start_idx=2, first plotted t≈2.0, avg_window=10 (last chunk may be smaller).\n",
      "Dataset 47: start_idx=2, first plotted t≈2.0, avg_window=10 (last chunk may be smaller).\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/SAL-Reviewer/Plots/047_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 59/105...\n",
      "Dataset 59: start_idx=2, first plotted t≈2.0, avg_window=10 (last chunk may be smaller).\n",
      "Dataset 59: start_idx=2, first plotted t≈2.0, avg_window=10 (last chunk may be smaller).\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/SAL-Reviewer/Plots/059_SAL_Absolute_Difference_Percentage_Dataset.png\n",
      "Processing dataset 63/105...\n",
      "Dataset 63: start_idx=2, first plotted t≈2.0, avg_window=10 (last chunk may be smaller).\n",
      "Dataset 63: start_idx=2, first plotted t≈2.0, avg_window=10 (last chunk may be smaller).\n",
      "SAL Absolute difference plot saved at: /work/bb1070/b382483/Final/L=2km_new/SAL-Reviewer/Plots/063_SAL_Absolute_Difference_Percentage_Dataset.png\n"
     ]
    }
   ],
   "source": [
    "if __name__ == \"__main__\":\n",
    "    main()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "fe938f02-9bfc-4912-a421-f541accb5f9f",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "env-ubc",
   "language": "python",
   "name": "env-ubc"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.19"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
